### ISSUE TITLE
missing

### ISSUE THREAD

**Issue by nachiket** [patric-r/ICQExport#1]
Where I try to run:
`java -jar ICQExport.jar` or `java -cp lib/ -jar ICQExport.jar` I get the following error. I also tried setting CLASSPATH to no avail.

```
ICQExport - exports ICQ database files (prior to version 2003b) to HTML
Processing dat file
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Maps
	at icqexport.ICQExport.main(ICQExport.java:112)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 6 more
```

**Comment by patric-r** [comment]
From the stacktrace, it looks like you have a special java runtime with eclipse dependencies which behaves differently than an openjdk derivate.
What does `java -version` print? Can you retry e.g. with AdoptJDK?

**Comment by nachiket** [comment]
It is OpenJDK on a MacOSX Intel.

```
java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)
```

**Comment by nachiket** [comment]
I tried to compile from source and it still fails as follows:
Compiling..
```
 $ javac -d build -cp lib/guava-18.0.jar src/icqexport/ICQExport.java 

src/com/mindprod/ledatastream/LERandomAccessFile.java
src/icqexport/ICQExport.java:258: warning: [removal] Long(String) in Long has been deprecated and marked for removal
						new Long(props.get("LastOnlineTime")).longValue() * 1000L);
						^
1 warning
```

Building an executable JAR
```
$ cd build
$ jar -cmvf manifest.txt ICQExport.jar com/mindprod/ledatastream/LERandomAccessFile.class  icqexport/ICQExport.class
added manifest
adding: com/mindprod/ledatastream/LERandomAccessFile.class(in = 4780) (out= 2058)(deflated 56%)
adding: icqexport/ICQExport.class(in = 10046) (out= 5149)(deflated 48%)
```

Trying to run it a few different ways:
```
 $ java -jar ICQExport.jar ../lib/guava-18.0.jar
ICQExport - exports ICQ database files (prior to version 2003b) to HTML
Processing dat file
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Maps
	at icqexport.ICQExport.main(ICQExport.java:112)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 1 more
```

If I run it directly, a GUI shows up that lets me pick the folder but then crashes after choosing the DAT file.
```
$ java -jar ICQExport.jar
ICQExport - exports ICQ database files (prior to version 2003b) to HTML
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Processing dat file
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Maps
	at icqexport.ICQExport.main(ICQExport.java:112)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 1 more
```

**Comment by nachiket** [comment]
Oh and `manifest.txt` is just one line:
```
Main-Class: icqexport.ICQExport
```

**Comment by patric-r** [comment]
I think you're on the right track. After building your custom jar, instead of executing
`$ java -jar ICQExport.jar ../lib/guava-18.0.jar`
can you try
`java -cp ICQExport.jar:../lib/guava-18.0.jar icqexport.ICQExport` instead?

**Comment by nachiket** [comment]
That almost worked! Now on selecting a DAT file, I get this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: icqexport/ICQExport$Message
	at icqexport.ICQExport.main(ICQExport.java:150)
Caused by: java.lang.ClassNotFoundException: icqexport.ICQExport$Message
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
```

**Comment by nachiket** [comment]
Actually found the `jar` command bug and it works now!!! Thanks.
```
jar -cmvf manifest.txt ICQExport.jar com/mindprod/ledatastream/LERandomAccessFile.class  icqexport/ICQExport.class icqexport/ICQExport\$Message.class
```
